---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Check OS version
      assert:
        that:
          - (ansible_distribution == "Slackware" and ansible_distribution_major_version | int >= 15) or (ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 11) or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
        msg: "Unsupported operating system"
    #- include: tasks/sudoers.yml
    - include: tasks/lynis.yml
    - include: tasks/filesystem.yml
    - include: tasks/ca-certs.yml
    - include: tasks/debian_packages.yml
    - include: tasks/audit.yml
      tags: audit
    - include: tasks/login_defs.yml
    - include: tasks/pam.yml
    - include: tasks/services.yml
    - include: tasks/kernel.yml
    - include: tasks/services-accounting.yml
    - include: tasks/apparmor.yml
    - include: tasks/logging.yml
    - include: tasks/misc.yml
    - include: tasks/banners.yml
    - include: tasks/network.yml
    - include: tasks/entropy.yml
    #- include: tasks/aide.yml
    #- include: tasks/rkhunter.yml
    #- include: tasks/clamav.yml
    #- include: tasks/display_managers.yml
    - include: tasks/apache.yml

  handlers:
    - include: tasks/handlers.yml
