---
- name: Install AppArmor
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
  apt:
    name: ['apparmor', 'apparmor-profiles', 'apparmor-utils']
    update_cache: yes
  tags:
  - packages
# https://github.com/raspberrypi/linux/pull/1698
- name: Add lsm=apparmor to /boot/cmdline.txt (Raspbian)
  replace:
    path: /boot/cmdline.txt
    # https://stackoverflow.com/a/61974725
    regexp: '^(.(?!.*\blsm=apparmor\b).*)$'
    replace: '\1 lsm=apparmor'
  become: yes
  when: ansible_distribution == "Debian" and ansible_lsb.id == "Raspbian"
# https://github.com/pyllyukko/harden.sh/wiki/AppArmor
- name: Enable extra profiles
  block:
  - name: Copy extra profiles
    copy:
      src: /usr/share/apparmor/extra-profiles/{{ item }}
      dest: /etc/apparmor.d/{{ item }}
      owner: root
      group: root
      mode: '0600'
      remote_src: yes
    with_items: '{{ apparmor_profiles }}'
  - name: Enable extra profiles
    command: /usr/sbin/aa-enforce /etc/apparmor.d/{{ item }}
    with_items: '{{ apparmor_profiles }}'
  vars:
    apparmor_profiles:
      - usr.lib.firefox.firefox
      - usr.lib.firefox.firefox.sh
      - usr.lib.firefox.mozilla-xremote-client
      - etc.cron.daily.logrotate
      - etc.cron.daily.slocate.cron
      - etc.cron.daily.tmpwatch
      - sbin.dhclient-script
      - sbin.dhcpcd
      - usr.bin.passwd
      - usr.bin.wireshark
      - usr.sbin.dhcpd
      #- usr.sbin.sshd
      - usr.sbin.useradd
      - usr.sbin.userdel
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
