---
- name: CA certs
  block:
  - name: Remove /etc/ssl/certs/ssl-cert-snakeoil.pem
    file:
      path: /etc/ssl/certs/ssl-cert-snakeoil.pem
      state: absent
    tags:
    - pki
    - configuration
    notify: "Run update-ca-certificates"
  - name: Install ca-certificates package (Debian)
    when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
    apt:
      name: ca-certificates
      update_cache: yes
    tags:
    - packages
    - pki
  - name: Copy ca-certificates.conf
    when: ansible_os_family != "RedHat"
    copy:
      src: "{{ playbook_dir }}/newconfs/ca-certificates.conf.new"
      dest: /etc/ca-certificates.conf
    tags:
    - configuration
    - pki
    notify: "Run update-ca-certificates"
  - name: Install OpenSSL (Slackware)
    when: ansible_distribution == "Slackware"
    command: slackpkg -batch=on -default_answer=y install openssl
    tags: packages
  become: yes
