---
- name: CA certs
  become: yes
  block:
  - name: Remove /etc/ssl/certs/ssl-cert-snakeoil.pem
    file:
      path: /etc/ssl/certs/ssl-cert-snakeoil.pem
      state: absent
    tags:
      - pki
      - configuration
    notify: "Run update-ca-certificates"
  - name: Install ca-certificates package (Debian)
    when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
    apt:
      name: ca-certificates
      update_cache: yes
    tags:
      - packages
      - pki
      - debian
  - name: Copy ca-certificates.conf
    when: ansible_os_family != "RedHat"
    copy:
      src: "{{ playbook_dir }}/newconfs/ca-certificates.conf.new"
      dest: /etc/ca-certificates.conf
      owner: root
      group: root
      mode: '0644'
    tags:
      - configuration
      - pki
    notify: "Run update-ca-certificates"
  - name: Install OpenSSL (Slackware)
    when: ansible_distribution == "Slackware"
    slackpkg:
      name: openssl
      state: present
    tags:
      - packages
      - slackware
