---
- name: ClamAV
  become: true
  tags: clamav
  block:
    - name: Install ClamAV (Debian)
      ansible.builtin.apt:
        name: ['clamav', 'clamav-daemon']
        update_cache: true
      when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
      tags:
        - packages
        - services
        - debian
    - name: Determine ClamAV sysconfdir
      ansible.builtin.shell: set -o pipefail; clamconf | awk '/^Checking configuration files in/{print$5}' # noqa no-changed-when
      register: clamav_sysconfdir
      tags: check
      args:
        executable: /bin/bash
    - name: Verify ClamAV sysconfdir
      ansible.builtin.assert:
        that:
          - clamav_sysconfdir.stdout | length > 0
          - clamav_sysconfdir.stdout | regex_search('^/etc')
      tags: check
    - name: Generate fresh configs
      ansible.builtin.shell: /usr/bin/clamconf -g {{ item }}.conf 1>{{ clamav_sysconfdir.stdout }}/{{ item }}.conf.new
      with_items:
        - freshclam
        - clamd
      tags: configuration
      changed_when: true
      args:
        executable: /bin/bash
    - name: Comment out Example lines
      ansible.builtin.replace:
        path: '{{ clamav_sysconfdir.stdout }}/{{ item }}.conf.new'
        regexp: '^(Example)$'
        replace: '#\g<1>'
      with_items:
        - freshclam
        - clamd
      tags: configuration
    - name: mkdir /var/run/clamav/
      ansible.builtin.file:
        path: /var/run/clamav
        state: directory
        owner: clamav
        group: clamav
        mode: '0771'
    # https://docs.clamav.net/manual/Usage/Configuration.html#clamdconf
    - name: Configure ClamAV
      ansible.builtin.replace:
        path: '{{ clamav_sysconfdir.stdout }}/clamd.conf.new'
        regexp: '^#?({{ item.key }} ).*$'
        replace: '\g<1>{{ item.value }}'
        validate: '/bin/grep "^{{ item.key }} {{ item.value }}$" %s'
      with_dict: "{{ clamav_settings }}"
      vars:
        clamav_settings:
          LogTime: "no"
          LogSyslog: "yes"
          LogFacility: LOG_LOCAL6
          ExtendedDetectionInfo: "yes"
          CrossFilesystems: "yes"
          DetectPUA: "yes"
          HeuristicAlerts: "yes"
          HeuristicScanPrecedence: "no"
          AlertBrokenExecutables: "yes"
          AlertBrokenMedia: "yes"
          ScanPE: "yes"
          ScanELF: "yes"
          ScanOLE2: "yes"
          ScanPDF: "yes"
          ScanSWF: "yes"
          ScanXMLDOCS: "yes"
          ScanHWP3: "yes"
          ScanMail: "yes"
          PhishingSignatures: "yes"
          PhishingScanURLs: "yes"
          ScanHTML: "yes"
          ScanArchive: "yes"
          Bytecode: "yes"
          BytecodeSecurity: Paranoid
          LocalSocket: /run/clamav/clamd.sock
          LocalSocketMode: 660
          PidFile: /run/clamav/clamd.pid
          User: clamav
          AlertOLE2Macros: "yes"
          FixStaleSocket: "yes"
          DatabaseDirectory: /var/lib/clamav
      tags: configuration
    # https://docs.clamav.net/manual/Usage/Configuration.html#freshclamconf
    - name: Configure freshclam
      ansible.builtin.replace:
        path: '{{ clamav_sysconfdir.stdout }}/freshclam.conf.new'
        regexp: '^#?({{ item.key }} ).*$'
        replace: '\g<1>{{ item.value }}'
        validate: '/bin/grep "^{{ item.key }} {{ item.value }}$" %s'
      with_dict: "{{ freshclam_settings }}"
      vars:
        freshclam_settings:
          LogTime: "no"
          LogFacility: LOG_LOCAL6
          ScriptedUpdates: "yes"
          CompressLocalDatabase: "no"
          ReceiveTimeout: 300
          TestDatabases: "yes"
          Bytecode: "yes"
          DatabaseMirror: database.clamav.net
          DatabaseOwner: clamav
          PidFile: /run/clamav/freshclam.pid
          DatabaseDirectory: /var/lib/clamav
      tags: configuration
    - name: Copy new ClamAV configurations into place
      ansible.builtin.copy:
        remote_src: true
        src: '{{ clamav_sysconfdir.stdout }}/{{ item }}.conf.new'
        dest: '{{ clamav_sysconfdir.stdout }}/{{ item }}.conf'
        owner: root
        group: root
        mode: '0644'
        backup: true
      with_items:
        - freshclam
        - clamd
      tags: configuration
    - name: Remove .new configs
      ansible.builtin.file:
        path: '{{ clamav_sysconfdir.stdout }}/{{ item }}.conf.new'
        state: absent
      with_items:
        - clamd
        - freshclam
    # Make the dir and the necessary files readable by other users so they can run clamscan
    - name: Make /var/lib/clamav/ +rx
      ansible.builtin.file:
        path: /var/lib/clamav/
        mode: '0755'
      tags: permissions
    # "CLD files are uncompressed and unsigned versions of the CVD that have had CDIFFs applied"
    - name: Make /var/lib/clamav/*.c[lv]d +r
      ansible.builtin.file:
        path: /var/lib/clamav/{{ item }}
        mode: '0644'
      with_items:
        - daily.cld
        - daily.cvd
        - bytecode.cld
        - bytecode.cvd
        - main.cvd
        - main.cld
        - general_officemacros.yar
      register: result
      failed_when:
        - result.failed == true
        - result.state != "absent"
      tags: permissions
    # https://blog.didierstevens.com/2017/02/15/quickpost-clamav-and-zip-file-decryption/
    - name: Create a password signature file
      ansible.builtin.copy:
        dest: /var/lib/clamav/passwords.pwdb
        owner: root
        group: root
        mode: '0644'
        content: |
          ZipPasswordInfected;Engine:81-255;0;infected
      tags: configuration
    # https://docs.clamav.net/manual/Signatures/YaraRules.html
    # https://github.com/Neo23x0/signature-base
    #
    # TODO: This needs to be continued to include more YARA rules,
    #       but it's really tedious as ClamAV doesn't support all the YARA features/extensions.
    #
    # LibClamAV Error: yyerror(): undefined identifier "filename"
    # LibClamAV Error: yyerror(): undefined identifier "pe"
    # LibClamAV Error: yyerror(): undefined identifier "uint32be"
    # LibClamAV Warning: load_oneyara[verify]: wide modifier [w] is not supported for regex subsigs
    #
    # So far we have included all the working rules from (e36e80a):
    # * apt_*.yar
    # * crime_*.yar
    # * expl_*.yar
    # * exploit_*.yar
    # * mal_*.yar
    # * [pst]*.yar
    - name: Download YARA rules
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/Neo23x0/signature-base/master/yara/{{ item }}"
        dest: /var/lib/clamav/
        owner: root
        group: root
        mode: '0644'
      with_items:
        - apt_aa19_024a.yar
        - apt_alienspy_rat.yar
        - apt_apt17_malware.yar
        - apt_apt28_drovorub.yar
        - apt_apt29_grizzly_steppe.yar
        - apt_apt29_nobelium_apr22.yar
        - apt_apt30_backspace.yar
        - apt_apt34.yar
        - apt_apt37.yar
        - apt_apt3_bemstour.yar
        - apt_apt6_malware.yar
        - apt_ar18_165a.yar
        - apt_area1_phishing_diplomacy.yar
        - apt_aus_parl_compromise.yar
        - apt_backdoor_ssh_python.yar
        - apt_backspace.yar
        - apt_beepservice.yar
        - apt_between-hk-and-burma.yar
        - apt_bitter.yar
        - apt_blackenergy.yar
        - apt_blackenergy_installer.yar
        - apt_bluetermite_emdivi.yar
        - apt_buckeye.yar
        - apt_casper.yar
        - apt_cheshirecat.yar
        - apt_cloudatlas.yar
        - apt_cloudduke.yar
        - apt_cn_netfilter.yar
        - apt_cn_pp_zerot.yar
        - apt_cn_reddelta.yar
        - apt_codoso.yar
        - apt_coreimpact_agent.yar
        - apt_danti_svcmondr.yar
        - apt_darkcaracal.yar
        - apt_deeppanda.yar
        - apt_derusbi.yar
        - apt_dnspionage.yar
        - apt_dtrack.yar
        - apt_dubnium.yar
        - apt_duqu1_5_modules.yar
        - apt_duqu2.yar
        - apt_dustman.yar
        - apt_emissary.yar
        - apt_eqgrp_apr17.yar
        - apt_eqgrp_triangulation_jun23.yar
        - apt_eternalblue_non_wannacry.yar
        - apt_f5_bigip_expl_payloads.yar
        - apt_fakem_backdoor.yar
        - apt_fancybear_computrace_agent.yar
        - apt_fancybear_dnc.yar
        - apt_fancybear_osxagent.yar
        - apt_fidelis_phishing_plain_sight.yar
        - apt_fin7_backdoor.yar
        - apt_fin8.yar
        - apt_four_element_sword.yar
        - apt_fujinama_rat.yar
        - apt_furtim.yar
        - apt_fvey_shadowbroker_dec16.yar
        - apt_fvey_shadowbroker_jan17.yar
        - apt_ghostdragon_gh0st_rat.yar
        - apt_glassRAT.yar
        - apt_goldenspy.yar
        - apt_hackingteam_rules.yar
        - apt_ham_tofu_chches.yar
        - apt_hellsing_kaspersky.yar
        - apt_hiddencobra_bankshot.yar
        - apt_hiddencobra_wiper.yar
        - apt_iamtheking.yar
        - apt_icefog.yar
        - apt_indetectables_rat.yar
        - apt_industroyer.yar
        - apt_irongate.yar
        - apt_irontiger.yar
        - apt_irontiger_trendmicro.yar
        - apt_ism_rat.yar
        - apt_kaspersky_duqu2.yar
        - apt_ke3chang.yar
        - apt_keylogger_cn.yar
        - apt_korplug_fast.yar
        - apt_kwampirs.yar
        - apt_laudanum_webshells.yar
        - apt_lazarus_aug20.yar
        - apt_lazarus_dec17.yar
        - apt_lazarus_gopuram.yar
        - apt_lazarus_jan21.yar
        - apt_lazarus_vhd_ransomware.yar
        - apt_leviathan.yar
        - apt_lnx_kobalos.yar
        - apt_lnx_linadoor_rootkit.yar
        - apt_magichound.yar
        - apt_mal_ilo_board_elf.yar
        - apt_mal_ru_snake_may23.yar
        - apt_miniasp.yar
        - apt_minidionis.yar
        - apt_mofang.yar
        - apt_molerats_jul17.yar
        - apt_moonlightmaze.yar
        - apt_muddywater.yar
        - apt_naikon.yar
        - apt_nanocore_rat.yar
        - apt_nazar.yar
        - apt_netwire_rat.yar
        - apt_nk_gen.yar
        - apt_nk_inkysquid.yar
        - apt_oilrig_chafer_mar18.yar
        - apt_onhat_proxy.yar
        - apt_op_cleaver.yar
        - apt_op_cloudhopper.yar
        - apt_op_shadowhammer.yar
        - apt_passcv.yar
        - apt_passthehashtoolkit.yar
        - apt_patchwork.yar
        - apt_plead_downloader.yar
        - apt_poisonivy.yar
        - apt_poisonivy_gen3.yar
        - apt_poseidon_group.yar
        - apt_poshspy.yar
        - apt_project_m.yar
        - apt_project_sauron_extras.yar
        - apt_promethium_neodymium.yar
        - apt_putterpanda.yar
        - apt_quarkspwdump.yar
        - apt_quasar_rat.yar
        - apt_quasar_vermin.yar
        - apt_ransom_darkbit_feb23.yar
        - apt_ransom_vicesociety_dec22.yar
        - apt_revenge_rat.yar
        - apt_rocketkitten_keylogger.yar
        - apt_royalroad.yar
        - apt_ru_crywiper.yar
        - apt_rwmc_powershell_creddump.yar
        - apt_sakula.yar
        - apt_sandworm_cyclops_blink.yar
        - apt_sandworm_exim_expl.yar
        - apt_saudi_aramco_phish.yar
        - apt_scanbox_deeppanda.yar
        - apt_scarcruft.yar
        - apt_seaduke_unit42.yar
        - apt_sednit_delphidownloader.yar
        - apt_servantshell.yar
        - apt_shamoon.yar
        - apt_shamoon2.yar
        - apt_sharptongue.yar
        - apt_shellcrew_streamex.yar
        - apt_sidewinder.yar
        - apt_skeletonkey.yar
        - apt_snaketurla_osx.yar
        - apt_snowglobe_babar.yar
        - apt_sofacy_cannon.yar
        - apt_sofacy_dec15.yar
        - apt_sofacy_fysbis.yar
        - apt_sofacy_jun16.yar
        - apt_sofacy_zebrocy.yar
        - apt_sphinx_moth.yar
        - apt_stealer_cisa_ar22_277a.yar
        - apt_stuxnet.yar
        - apt_stuxshop.yar
        - apt_sunspot.yar
        - apt_sysscan.yar
        - apt_ta18_074A.yar
        - apt_ta459.yar
        - apt_telebots.yar
        - apt_terracotta.yar
        - apt_terracotta_liudoor.yar
        - apt_tidepool.yar
        - apt_turla_neuron.yar
        - apt_turla_penquin.yar
        - apt_ua_caddywiper.yar
        - apt_ua_hermetic_wiper.yar
        - apt_ua_wiper_whispergate.yar
        - apt_uboat_rat.yar
        - apt_unc1151_ua.yar
        - apt_unc2447_sombrat.yar
        - apt_unc2546_dewmode.yar
        - apt_unc2891_mal_jan23.yar
        - apt_unit78020_malware.yar
        - apt_uscert_ta17-1117a.yar
        - apt_venom_linux_rootkit.yar
        - apt_volatile_cedar.yar
        - apt_vpnfilter.yar
        - apt_waterbear.yar
        - apt_waterbug.yar
        - apt_webmonitor_rat.yar
        - apt_webshell_chinachopper.yar
        - apt_wildneutron.yar
        - apt_win_plugx.yar
        - apt_winnti_hdroot.yar
        - apt_winnti_linux.yar
        - apt_winnti_ms_report_201701.yar
        - apt_woolengoldfish.yar
        - apt_xrat.yar
        - crime_academic_data_centers_camp_may20.yar
        - crime_andromeda_jun17.yar
        - crime_antifw_installrex.yar
        - crime_atm_javadipcash.yar
        - crime_atm_loup.yar
        - crime_atm_xfsadm.yar
        - crime_atm_xfscashncr.yar
        - crime_bad_patch.yar
        - crime_badrabbit.yar
        - crime_bazarbackdoor.yar
        - crime_bernhard_pos.yar
        - crime_bluenoroff_pos.yar
        - crime_buzus_softpulse.yar
        - crime_cmstar.yar
        - crime_cn_group_btc.yar
        - crime_cobalt_gang_pdf.yar
        - crime_covid_ransom.yar
        - crime_credstealer_generic.yar
        - crime_crypto_miner.yar
        - crime_cryptowall_svg.yar
        - crime_dearcry_ransom.yar
        - crime_dexter_trojan.yar
        - crime_dridex_xml.yar
        - crime_enfal.yar
        - crime_envrial.yar
        - crime_eternalrocks.yar
        - crime_fareit.yar
        - crime_fireball.yar
        - crime_gamaredon.yar
        - crime_goldeneye.yar
        - crime_gozi_crypter.yar
        - crime_guloader.yar
        - crime_h2miner_kinsing.yar
        - crime_hermes_ransom.yar
        - crime_icedid.yar
        - crime_kins_dropper.yar
        - crime_kr_malware.yar
        - crime_kraken_bot1.yar
        - crime_kriskynote.yar
        - crime_locky.yar
        - crime_loki_bot.yar
        - crime_malumpos.yar
        - crime_malware_generic.yar
        - crime_malware_set_oct16.yar
        - crime_maze_ransomware.yar
        - crime_mikey_trojan.yar
        - crime_mirai.yar
        - crime_mywscript_dropper.yar
        - crime_nkminer.yar
        - crime_nopetya_jun17.yar
        - crime_ole_loadswf_cve_2018_4878.yar
        - crime_parallax_rat.yar
        - crime_phish_gina_dec15.yar
        - crime_ransom_conti.yar
        - crime_ransom_generic.yar
        - crime_ransom_germanwiper.yar
        - crime_ransom_lockergoga.yar
        - crime_ransom_prolock.yar
        - crime_ransom_revil.yar
        - crime_ransom_robinhood.yar
        - crime_ransom_stealbit_lockbit.yar
        - crime_rat_parallax.yar
        - crime_rombertik_carbongrabber.yar
        - crime_shifu_trojan.yar
        - crime_socgholish.yar
        - crime_stealer_exfil_zip.yar
        - crime_teledoor.yar
        - crime_upatre_oct15.yar
        - crime_wannacry.yar
        - crime_wsh_rat.yar
        - crime_xbash.yar
        - crime_zeus_panda.yar
        - crime_zloader_maldocs.yar
        - expl_adselfservice_cve_2021_40539.yar
        - expl_cve_2021_1647.yar
        - expl_cve_2021_40444.yar
        - expl_cve_2022_41040_proxynoshell.yar
        - expl_cve_2022_46169_cacti.yar
        - expl_ivanti_epmm_mobileiron_cve_2023_35078.yar
        - expl_keepass_cve_2023_24055.yar
        - expl_libssh_cve_2023_2283_jun23.yar
        - expl_log4j_cve_2021_44228.yar
        - expl_macos_switcharoo_dec22.yar
        - expl_manageengine_jan23.yar
        - expl_proxyshell.yar
        - expl_spring4shell.yar
        - exploit_cve_2014_4076.yar
        - exploit_cve_2015_1674.yar
        - exploit_cve_2015_1701.yar
        - exploit_cve_2015_2426.yar
        - exploit_cve_2015_2545.yar
        - exploit_cve_2015_5119.yar
        - exploit_cve_2017_9800.yar
        - exploit_cve_2021_31166.yar
        - exploit_cve_2021_33766_proxytoken.yar
        - exploit_cve_2022_22954_vmware_workspace_one.yar
        - exploit_cve_2023_38146.yar
        - exploit_f5_bigip_cve_2021_22986_log.yar
        - exploit_gitlab_cve_2021_22205.yar
        - exploit_shitrix.yar
        - exploit_uac_elevators.yar
        - mal_avemaria_rat.yar
        - mal_codecov_hack.yar
        - mal_crime_unknown.yar
        - mal_ducktail_compromised_certs_jun23.yar
        - mal_efile_apr23.yar
        - mal_lnx_implant_may22.yar
        - mal_passwordstate_backdoor.yar
        - mal_qbot_payloads.yar
        - mal_ransom_esxi_attacks_feb23.yar
        - mal_ransom_lorenz.yar
        - mal_ru_sparepart_dec22.yar
        - pua_cryptocoin_miner.yar
        - pua_xmrig_monero_miner.yar
        - pup_lightftp.yar
        - spy_equation_fiveeyes.yar
        - spy_querty_fiveeyes.yar
        - spy_regin_fiveeyes.yar
        - susp_vulndriver_hp_hardware_diagnostics_etdsupp_may23.yar
        - thor-webshells.yar
        - threat_lenovo_superfish.yar
