---
- name: Install security software
  tags: debian
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
  become: true
  block:
    - name: Install security software
      ansible.builtin.apt:
        name: "{{ packages }}"
        update_cache: true
      vars:
        packages:
          - bootlogd
          - tiger
          - autolog
          - chkrootkit
          - needrestart
          - arpwatch
          - usbguard
          - unattended-upgrades
          - checksecurity
          - checksec
          - hardening-runtime
          - apt-show-versions
      tags:
        - packages
        - services
    - name: AIDE
      ansible.builtin.import_tasks: aide.yml
    - name: Symlink /usr/lib/tiger/systems/Linux/5 -> 4
      ansible.builtin.file:
        src: /usr/lib/tiger/systems/Linux/4
        dest: /usr/lib/tiger/systems/Linux/5
        state: link
      tags: configuration

- name: Comment out user.max_user_namespaces=0 in /usr/lib/sysctl.d/10-hardening.conf
  tags:
    - debian
    - configuration
    - kernel
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
  become: true
  #notify: "Load sysctl settings"
  ansible.builtin.replace:
    path: /usr/lib/sysctl.d/10-hardening.conf
    regexp: "^(user.max_user_namespaces = 0)$"
    replace: '#\1'

# debsecan
- name: debsecan
  when: ansible_distribution == "Debian"
  tags:
    - debsecan
    - debian
  become: true
  block:
    - name: Install debsecan
      ansible.builtin.apt:
        name: debsecan
      tags: packages
    - name: Configure debsecan
      ansible.builtin.debconf:
        name: debsecan
        question: debsecan/suite
        vtype: select
        value: "{{ ansible_distribution_release }}"
      tags: configuration

# debsums
- name: debsums
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
  become: true
  tags:
    - debsums
    - debian
  block:
    - name: Install debsums
      ansible.builtin.apt:
        name: debsums
      tags: packages
    - name: Enable weekly debsums run
      ansible.builtin.replace:
        path: /etc/default/debsums
        regexp: '^(CRON_CHECK=).*'
        replace: '\g<1>weekly'
      tags: configuration

# TODO: Kali has chkrootkit conf in /etc/chkrootkit/
- name: Configure chkrootkit
  become: true
  when: ansible_distribution == "Debian"
  tags:
    - configuration
    - chkrootkit
    - debian
  block:
    - name: Create /etc/chkrootkit.ignore
      ansible.builtin.copy:
        dest: /etc/chkrootkit.ignore
        owner: root
        group: root
        mode: '0400'
        content: |
          ^-e The following suspicious files and directories were found:$
          ^$
          ^ ?/usr/lib/debug/\.build-id$
          ^ ?/usr/lib/libreoffice/share/\.registry$
          ^ ?/usr/lib/ruby/vendor_ruby/rubygems/ssl_certs/\.document$
          ^ ?/usr/lib/pypy/lib_pypy/ctypes_config_cache/\.empty$
          ^eth[0-9]+: PACKET SNIFFER\(/usr/sbin/dhcpcd\[[0-9]+\](, /usr/sbin/collectd\[[0-9]+\])?\)$
    - name: Configure /etc/cron.daily/chkrootkit to use chkrootkit.ignore
      ansible.builtin.replace:
        path: /etc/cron.daily/chkrootkit
        regexp: '^(IGNORE_FILE=).*'
        replace: '\g<1>/etc/chkrootkit.ignore'
    - name: Enable daily chkrootkit run
      ansible.builtin.replace:
        path: /etc/chkrootkit.conf
        regexp: '^(RUN_DAILY=).*'
        replace: '\g<1>"true"'
