---
# https://github.com/canonical/lightdm#configuration
- name: Stat /etc/lightdm/lightdm.conf
  stat:
    path: /etc/lightdm/lightdm.conf
  register: stat_result
  tags:
  - network
  - configuration
- name: Configure LightDM
  tags: configuration
  when: stat_result.stat.exists == True
  block:
  - name: Disable VNC in LightDM
    ini_file:
      path: /etc/lightdm/lightdm.conf
      section: VNCServer
      option: enabled
      value: "false"
    tags: network
  - name: Hide user list and disallow guest login in LightDM
    ini_file:
      path: /etc/lightdm/lightdm.conf
      section: Seat:*
      option: '{{ item.key }}'
      value: '{{ item.value }}'
    with_dict:
      greeter-hide-users: "true"
      allow-guest: "false"
  become: yes
# CIS Debian Linux 10 Benchmark v1.0.0 - 02-13-2020
# 1.8.2 Ensure GDM login banner is configured
- name: Configure GDM3
  tags:
  - configuration
  - banners
  replace:
    regexp: '^(# ?)?({{ item.key }})=.+$'
    replace: '\g<2>={{ item.value }}'
    path: /etc/gdm3/greeter.dconf-defaults
  with_dict:
    disable-user-list: "true"
    banner-message-enable: "true"
    banner-message-text: "'Authorized uses only'"
  become: yes
  register: result
  failed_when:
    - result.failed == true
    - result.msg != "Path /etc/gdm3/greeter.dconf-defaults does not exist !"
