---
# Install rng-tools when TRNG is available and in use
- name: Read /sys/class/misc/hw_random/rng_current
  slurp:
    src: /sys/class/misc/hw_random/rng_current
  register: rng_current
  tags: rng
- name: Use rng-tools
  tags: rng
  block:
  - name: Install rng-tools
    apt:
      name: rng-tools
      update_cache: yes
    tags: packages
  - name: Start & enable rng-tools service
    service:
      name: rng-tools
      state: started
      enabled: yes
    tags: services
  when: rng_current['content'] | b64decode != "none\n" and ansible_distribution == "Debian"
  become: yes
