---
- name: Set file permissions/ownership for sudoers
  file:
    path: /etc/{{ item }}
    mode: g-w,o-rwx
    owner: root
    group: root
  become: yes
  tags: permissions
  with_items:
    - sudoers.d
    - sudoers
