---
- name: Set file permissions/ownership for sudoers
  file:
    path: /etc/{{ item }}
    mode: g-w,o-rwx
    owner: root
    group: root
  become: true
  tags:
    - permissions
    - sudo
  with_items:
    - sudoers.d
    - sudoers
