---
- name: rkhunter
  tags: rkhunter
  become: true
  block:
  - name: Install rkhunter (Debian)
    ansible.builtin.apt:
      name: rkhunter
      update_cache: true
    when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
    tags:
      - packages
      - debian
  - name: 'Create /etc/rkhunter.conf'
    ansible.builtin.template:
      src: "{{ playbook_dir }}/templates/rkhunter.conf.j2"
      dest: /etc/rkhunter.conf
      mode: '0400'
      owner: root
      group: root
    tags: configuration
    notify: "Create rkhunter.dat"
  # https://sourceforge.net/p/rkhunter/rkh_code/ci/master/tree/files/FAQ: "3.3) How can I automatically run Rootkit Hunter every day?"
  # We don't use --update as rkhunter.sourceforge.net doesn't have HTTPS
  - name: Add rkhunter cronjob
    ansible.builtin.cron:
      name: "Run rkhunter"
      minute: "30"
      hour: "5"
      job: "/usr/bin/test -x /usr/bin/rkhunter && /usr/bin/rkhunter --cronjob --rwo"
    when: ansible_distribution != "Debian"
    tags: configuration
  - name: Enable daily rkhunter check in Debian
    ansible.builtin.replace:
      path: /etc/default/rkhunter
      regexp: '^(CRON_DAILY_RUN=).*'
      replace: '\g<1>"yes"'
    when: ansible_distribution == "Debian"
    tags:
      - configuration
      - debian
