---
- name: Check SSH daemon service state
  ansible.builtin.service_facts:
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
  tags:
    - services
    - ssh
    - debian
    - check
- name: Check SSH daemon service state (Slackware)
  become: true
  ansible.builtin.stat:
    path: /etc/rc.d/rc.sshd
  register: rc_sshd
  tags:
    - ssh
    - slackware
    - check
# This is used in sshd_config.j2 template(s)
- name: Stat /etc/krb5.keytab
  ansible.builtin.stat:
    path: /etc/krb5.keytab
  register: stat_keytab
  tags:
    - ssh
    - check
- name: Harden SSH daemon configuration
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/sshd_config-{{ ansible_distribution }}.j2"
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    owner: root
    group: root
    mode: '0600'
    backup: true
  register: result
  # sshd validation fails when the hostkeys do not exist
  failed_when:
    - result.failed == true
    - '"sshd: no hostkeys available -- exiting." not in result.stderr'
  tags:
    - services
    - configuration
    - ssh
  notify:
    - "Restart sshd (Slackware)"
    - "Restart sshd (Debian)"
  become: true
  # Skip the task in Debian if ssh.service does not exist
  when: >
    ((ansible_distribution == "Debian" or ansible_distribution == "Kali") and ansible_facts.services.ssh is defined) or
    (ansible_distribution == "Slackware" and rc_sshd.stat.exists and rc_sshd.stat.xusr)
- name: Harden SSH client configuration
  tags:
    - configuration
    - slackware
    - ssh
  become: true
  when: ansible_distribution == "Slackware"
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/ssh_config-{{ ansible_distribution }}.j2"
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: '0644'
